configure infra

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,32 +4,40 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here   
+      # Add parameter here
+      workflowId:
+        type: string   
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
             # Your code here
-            exit 1
+            aws cloudformation delete-stack \
+              --stack-name "frontend-stack-<< parameters.workflowId >>"
+            aws cloudformation delete-stack \
+              --stack-name "backend-stack-<< parameters.workflowId >>"
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+      # Add parameter here  
+      workflowId:
+        type: string            
     steps:
       - run:
           name: Revert migrations
           # Add when this will run
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS=
             SUCCESS = 1
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
+            cd ~/project/backend
+            npm install
             #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+            npm run migrations:revert
             fi
             
 jobs:
@@ -179,8 +187,35 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure      
-          
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment:
+          workflowId: "${CIRCLE_WORKFLOW_ID}"
+
+  configure-infrastructure:
+      docker:
+        - image: ansible/ansible
+      steps:
+        # Checkout code from git
+        - checkout
+        # Add ssh keys with fingerprint
+        - add_ssh_keys:
+            fingerprints:
+            - "b0:64:61:b7:03:d2:89:49:66:80:04:01:97:b6:cc:fe"
+        # attach workspace
+        - attach_workspace:
+            at: ~/
+        - run:
+            name: Install dependencies
+            command: |
+              # Your code here
+              exit 1
+        - run:
+            name: Configure server
+            command: |
+              # Your code here
+              exit 1
+        # Here's where you will add some code to rollback on failure 
+            
 workflows:
   default:
     jobs:
